<?php

namespace ContainerBoKqwIL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0ogbHxoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0ogbHxo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0ogbHxo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'produto' => ['privates', '.errored..service_locator.0ogbHxo.App\\Entity\\Produtos', NULL, 'Cannot autowire service ".service_locator.0ogbHxo": it references class "App\\Entity\\Produtos" but no such service exists.'],
            'produtosRepository' => ['privates', 'App\\Repository\\ProdutosRepository', 'getProdutosRepositoryService', true],
        ], [
            'produto' => 'App\\Entity\\Produtos',
            'produtosRepository' => 'App\\Repository\\ProdutosRepository',
        ]);
    }
}
