<?php

namespace ContainerBoKqwIL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ru5oKGCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ru5oKGC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ru5oKGC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CaracteristicasController::delete' => ['privates', '.service_locator.VEbWT9.', 'get_ServiceLocator_VEbWT9_Service', true],
            'App\\Controller\\CaracteristicasController::edit' => ['privates', '.service_locator.VEbWT9.', 'get_ServiceLocator_VEbWT9_Service', true],
            'App\\Controller\\CaracteristicasController::index' => ['privates', '.service_locator.Ft6qwB7', 'get_ServiceLocator_Ft6qwB7Service', true],
            'App\\Controller\\CaracteristicasController::new' => ['privates', '.service_locator.Ft6qwB7', 'get_ServiceLocator_Ft6qwB7Service', true],
            'App\\Controller\\CaracteristicasController::show' => ['privates', '.service_locator.DEBr_gL', 'get_ServiceLocator_DEBrGLService', true],
            'App\\Controller\\CategoriaController::delete' => ['privates', '.service_locator.QuHKGW_', 'get_ServiceLocator_QuHKGWService', true],
            'App\\Controller\\CategoriaController::edit' => ['privates', '.service_locator.QuHKGW_', 'get_ServiceLocator_QuHKGWService', true],
            'App\\Controller\\CategoriaController::index' => ['privates', '.service_locator.E0LM.2R', 'get_ServiceLocator_E0LM_2RService', true],
            'App\\Controller\\CategoriaController::new' => ['privates', '.service_locator.E0LM.2R', 'get_ServiceLocator_E0LM_2RService', true],
            'App\\Controller\\CategoriaController::show' => ['privates', '.service_locator.sPxlj5j', 'get_ServiceLocator_SPxlj5jService', true],
            'App\\Controller\\ProdutosController::delete' => ['privates', '.service_locator.0ogbHxo', 'get_ServiceLocator_0ogbHxoService', true],
            'App\\Controller\\ProdutosController::edit' => ['privates', '.service_locator.0ogbHxo', 'get_ServiceLocator_0ogbHxoService', true],
            'App\\Controller\\ProdutosController::index' => ['privates', '.service_locator.lotq7VK', 'get_ServiceLocator_Lotq7VKService', true],
            'App\\Controller\\ProdutosController::new' => ['privates', '.service_locator.lotq7VK', 'get_ServiceLocator_Lotq7VKService', true],
            'App\\Controller\\ProdutosController::show' => ['privates', '.service_locator.yaj8GS_', 'get_ServiceLocator_Yaj8GSService', true],
            'App\\Controller\\StoreController::index' => ['privates', '.service_locator.1yhhFB0', 'get_ServiceLocator_1yhhFB0Service', true],
            'App\\Controller\\StoreController::show' => ['privates', '.service_locator.1yhhFB0', 'get_ServiceLocator_1yhhFB0Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CaracteristicasController:delete' => ['privates', '.service_locator.VEbWT9.', 'get_ServiceLocator_VEbWT9_Service', true],
            'App\\Controller\\CaracteristicasController:edit' => ['privates', '.service_locator.VEbWT9.', 'get_ServiceLocator_VEbWT9_Service', true],
            'App\\Controller\\CaracteristicasController:index' => ['privates', '.service_locator.Ft6qwB7', 'get_ServiceLocator_Ft6qwB7Service', true],
            'App\\Controller\\CaracteristicasController:new' => ['privates', '.service_locator.Ft6qwB7', 'get_ServiceLocator_Ft6qwB7Service', true],
            'App\\Controller\\CaracteristicasController:show' => ['privates', '.service_locator.DEBr_gL', 'get_ServiceLocator_DEBrGLService', true],
            'App\\Controller\\CategoriaController:delete' => ['privates', '.service_locator.QuHKGW_', 'get_ServiceLocator_QuHKGWService', true],
            'App\\Controller\\CategoriaController:edit' => ['privates', '.service_locator.QuHKGW_', 'get_ServiceLocator_QuHKGWService', true],
            'App\\Controller\\CategoriaController:index' => ['privates', '.service_locator.E0LM.2R', 'get_ServiceLocator_E0LM_2RService', true],
            'App\\Controller\\CategoriaController:new' => ['privates', '.service_locator.E0LM.2R', 'get_ServiceLocator_E0LM_2RService', true],
            'App\\Controller\\CategoriaController:show' => ['privates', '.service_locator.sPxlj5j', 'get_ServiceLocator_SPxlj5jService', true],
            'App\\Controller\\ProdutosController:delete' => ['privates', '.service_locator.0ogbHxo', 'get_ServiceLocator_0ogbHxoService', true],
            'App\\Controller\\ProdutosController:edit' => ['privates', '.service_locator.0ogbHxo', 'get_ServiceLocator_0ogbHxoService', true],
            'App\\Controller\\ProdutosController:index' => ['privates', '.service_locator.lotq7VK', 'get_ServiceLocator_Lotq7VKService', true],
            'App\\Controller\\ProdutosController:new' => ['privates', '.service_locator.lotq7VK', 'get_ServiceLocator_Lotq7VKService', true],
            'App\\Controller\\ProdutosController:show' => ['privates', '.service_locator.yaj8GS_', 'get_ServiceLocator_Yaj8GSService', true],
            'App\\Controller\\StoreController:index' => ['privates', '.service_locator.1yhhFB0', 'get_ServiceLocator_1yhhFB0Service', true],
            'App\\Controller\\StoreController:show' => ['privates', '.service_locator.1yhhFB0', 'get_ServiceLocator_1yhhFB0Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CaracteristicasController::delete' => '?',
            'App\\Controller\\CaracteristicasController::edit' => '?',
            'App\\Controller\\CaracteristicasController::index' => '?',
            'App\\Controller\\CaracteristicasController::new' => '?',
            'App\\Controller\\CaracteristicasController::show' => '?',
            'App\\Controller\\CategoriaController::delete' => '?',
            'App\\Controller\\CategoriaController::edit' => '?',
            'App\\Controller\\CategoriaController::index' => '?',
            'App\\Controller\\CategoriaController::new' => '?',
            'App\\Controller\\CategoriaController::show' => '?',
            'App\\Controller\\ProdutosController::delete' => '?',
            'App\\Controller\\ProdutosController::edit' => '?',
            'App\\Controller\\ProdutosController::index' => '?',
            'App\\Controller\\ProdutosController::new' => '?',
            'App\\Controller\\ProdutosController::show' => '?',
            'App\\Controller\\StoreController::index' => '?',
            'App\\Controller\\StoreController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CaracteristicasController:delete' => '?',
            'App\\Controller\\CaracteristicasController:edit' => '?',
            'App\\Controller\\CaracteristicasController:index' => '?',
            'App\\Controller\\CaracteristicasController:new' => '?',
            'App\\Controller\\CaracteristicasController:show' => '?',
            'App\\Controller\\CategoriaController:delete' => '?',
            'App\\Controller\\CategoriaController:edit' => '?',
            'App\\Controller\\CategoriaController:index' => '?',
            'App\\Controller\\CategoriaController:new' => '?',
            'App\\Controller\\CategoriaController:show' => '?',
            'App\\Controller\\ProdutosController:delete' => '?',
            'App\\Controller\\ProdutosController:edit' => '?',
            'App\\Controller\\ProdutosController:index' => '?',
            'App\\Controller\\ProdutosController:new' => '?',
            'App\\Controller\\ProdutosController:show' => '?',
            'App\\Controller\\StoreController:index' => '?',
            'App\\Controller\\StoreController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
