<?php

namespace ContainerBoKqwIL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yaj8GSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yaj8GS_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yaj8GS_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'produto' => ['privates', '.errored..service_locator.yaj8GS_.App\\Entity\\Produtos', NULL, 'Cannot autowire service ".service_locator.yaj8GS_": it references class "App\\Entity\\Produtos" but no such service exists.'],
        ], [
            'produto' => 'App\\Entity\\Produtos',
        ]);
    }
}
