<?php

namespace ContainerBoKqwIL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaracteristicas2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VEbWT9..App\Entity\Caracteristicas' shared service.
     *
     * @return \App\Entity\Caracteristicas
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VEbWT9.": it references class "App\\Entity\\Caracteristicas" but no such service exists.');
    }
}
