<?php

namespace ContainerOAjKk2Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1yhhFB0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1yhhFB0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1yhhFB0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'produtoRepository' => ['privates', 'App\\Repository\\ProdutosRepository', 'getProdutosRepositoryService', true],
        ], [
            'produtoRepository' => 'App\\Repository\\ProdutosRepository',
        ]);
    }
}
