<?php

namespace ContainerOAjKk2Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaracteristicasService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DEBr_gL.App\Entity\Caracteristicas' shared service.
     *
     * @return \App\Entity\Caracteristicas
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DEBr_gL": it references class "App\\Entity\\Caracteristicas" but no such service exists.');
    }
}
