<?php

namespace Container712x1q2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VEbWT9_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VEbWT9.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VEbWT9.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'caracteristica' => ['privates', '.errored..service_locator.VEbWT9..App\\Entity\\Caracteristicas', NULL, 'Cannot autowire service ".service_locator.VEbWT9.": it references class "App\\Entity\\Caracteristicas" but no such service exists.'],
            'caracteristicasRepository' => ['privates', 'App\\Repository\\CaracteristicasRepository', 'getCaracteristicasRepositoryService', true],
        ], [
            'caracteristica' => 'App\\Entity\\Caracteristicas',
            'caracteristicasRepository' => 'App\\Repository\\CaracteristicasRepository',
        ]);
    }
}
