<?php

namespace Container712x1q2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lotq7VKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lotq7VK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lotq7VK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'produtosRepository' => ['privates', 'App\\Repository\\ProdutosRepository', 'getProdutosRepositoryService', true],
        ], [
            'produtosRepository' => 'App\\Repository\\ProdutosRepository',
        ]);
    }
}
