<?php

namespace Container712x1q2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProdutosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0ogbHxo.App\Entity\Produtos' shared service.
     *
     * @return \App\Entity\Produtos
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0ogbHxo": it references class "App\\Entity\\Produtos" but no such service exists.');
    }
}
