<?php

namespace ContainerDxVOx8z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EQdwpjPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EQdwpjP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EQdwpjP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProdutosController::delete' => ['privates', '.service_locator.0ogbHxo', 'get_ServiceLocator_0ogbHxoService', true],
            'App\\Controller\\ProdutosController::edit' => ['privates', '.service_locator.0ogbHxo', 'get_ServiceLocator_0ogbHxoService', true],
            'App\\Controller\\ProdutosController::index' => ['privates', '.service_locator.lotq7VK', 'get_ServiceLocator_Lotq7VKService', true],
            'App\\Controller\\ProdutosController::new' => ['privates', '.service_locator.lotq7VK', 'get_ServiceLocator_Lotq7VKService', true],
            'App\\Controller\\ProdutosController::show' => ['privates', '.service_locator.yaj8GS_', 'get_ServiceLocator_Yaj8GSService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\ProdutosController:delete' => ['privates', '.service_locator.0ogbHxo', 'get_ServiceLocator_0ogbHxoService', true],
            'App\\Controller\\ProdutosController:edit' => ['privates', '.service_locator.0ogbHxo', 'get_ServiceLocator_0ogbHxoService', true],
            'App\\Controller\\ProdutosController:index' => ['privates', '.service_locator.lotq7VK', 'get_ServiceLocator_Lotq7VKService', true],
            'App\\Controller\\ProdutosController:new' => ['privates', '.service_locator.lotq7VK', 'get_ServiceLocator_Lotq7VKService', true],
            'App\\Controller\\ProdutosController:show' => ['privates', '.service_locator.yaj8GS_', 'get_ServiceLocator_Yaj8GSService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\ProdutosController::delete' => '?',
            'App\\Controller\\ProdutosController::edit' => '?',
            'App\\Controller\\ProdutosController::index' => '?',
            'App\\Controller\\ProdutosController::new' => '?',
            'App\\Controller\\ProdutosController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ProdutosController:delete' => '?',
            'App\\Controller\\ProdutosController:edit' => '?',
            'App\\Controller\\ProdutosController:index' => '?',
            'App\\Controller\\ProdutosController:new' => '?',
            'App\\Controller\\ProdutosController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
