<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYgkaxtq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYgkaxtq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYgkaxtq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYgkaxtq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYgkaxtq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ygkaxtq',
    'container.build_id' => '269d74ef',
    'container.build_time' => 1661463791,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYgkaxtq');
