<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOAjKk2Q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOAjKk2Q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOAjKk2Q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOAjKk2Q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOAjKk2Q\App_KernelDevDebugContainer([
    'container.build_hash' => 'OAjKk2Q',
    'container.build_id' => 'b1b8281e',
    'container.build_time' => 1661371456,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOAjKk2Q');
