<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZuodmJ4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZuodmJ4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZuodmJ4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZuodmJ4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZuodmJ4\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZuodmJ4',
    'container.build_id' => '059a9343',
    'container.build_time' => 1661366336,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZuodmJ4');
